import { Character, CombatUnit, Quest } from './types';
import { calculateDerivedStats, createLoadoutFromEquipment, getSkillById, skills } from './game/rules';

const CHARACTER_IMAGE_BASE = 'https://pub-0b945c39f816498d833c1a7e27007410.r2.dev/';
export const characterImage = (name: string, type: '头像' | '立绘') =>
  `${CHARACTER_IMAGE_BASE}${encodeURIComponent(`${name}${type}.png`)}`;

export const fixedNpcImageNames = new Set([
  '贝尔娜',
  '妮娅',
  '帕琪',
  '萨菈',
  '露西',
  '绯欧菈',
  '小原',
  '玛洛',
  '艾米',
  '玛蒂',
  '蕾文',
  '贝琳',
  '布兰妲',
  '托兰娜',
  '奥薇',
  '茜尔七号',
  '莱恩',
  '约娜',
  '托比',
  '莉亚',
  '维芙',
  '露',
  '葛蕾娜',
  '诺拉',
  '伊薇',
  '巴丝',
  '埃利安',
  '梅莉莎',
  '罗薇',
  '佩拉',
]);

export const resolveCharacterImage = (
  name: string,
  type: '头像' | '立绘',
  options: { fixed?: boolean; raw?: unknown } = {},
) => {
  const raw = String(options.raw ?? '').trim();
  if (/^(https?:|data:|blob:|\/)/i.test(raw)) return raw;
  if (raw) {
    const baseName = raw.replace(/\.(png|jpg|jpeg|webp)$/i, '').replace(/头像$|立绘$/g, '') || name;
    return characterImage(baseName, type);
  }
  if (options.fixed || fixedNpcImageNames.has(name)) return characterImage(name, type);
  return '';
};

const skillRefs = (ids: string[]) =>
  ids.map(id => getSkillById(id)).filter((skill): skill is NonNullable<typeof skill> => Boolean(skill));

const npc = (input: Omit<Character, 'equipmentLoadout' | 'skills'> & { skills: string[] }): Character => ({
  ...input,
  equipmentLoadout: createLoadoutFromEquipment(input.equipmentIds),
  skills: skillRefs(input.skills),
});

export const eldredNPCs: Character[] = [
  npc({
    id: 'npc-berna',
    name: '贝尔娜',
    fullName: '白冠西门登记员贝尔娜',
    type: 'NPC登记',
    race: '矮人',
    raceId: 'dwarf',
    gender: '女',
    age: 25,
    affiliation: '神圣王国艾琳西亚',
    identity: '入城文书核验人',
    classId: 'paladin',
    profession: '城门登记员',
    avatarUrl: characterImage('贝尔娜', '头像'),
    portraitUrl: characterImage('贝尔娜', '立绘'),
    stats: calculateDerivedStats(4, 'paladin', { str: 2, dex: 4, vit: 5, int: 8, spr: 6 }, ['plain-holy-bell'], 'dwarf'),
    experience: 80,
    nextLevelExperience: 400,
    availableAttributePoints: 0,
    favorability: 0,
    relationshipStage: '陌生',
    equipmentIds: ['plain-holy-bell', 'field-robe'],
    activeSkillIds: ['berna-whistle-call', 'paladin-shield-line'],
    knownSkillIds: ['berna-whistle-call', 'paladin-shield-line', 'paladin-guard-step'],
    attributes: ['白冠西门登记权', '泥脚印辨识', '灾民日期核对'],
    skills: ['berna-whistle-call', 'paladin-shield-line'],
  }),
  npc({
    id: 'npc-nia',
    name: '妮娅',
    fullName: '风铃行会接待员妮娅',
    type: 'NPC登记',
    race: '人类',
    raceId: 'human',
    gender: '女',
    age: 24,
    affiliation: '七旗城风铃冒险者行会',
    identity: '委托分级与结算负责人',
    classId: 'sage',
    profession: '行会接待员',
    avatarUrl: characterImage('妮娅', '头像'),
    portraitUrl: characterImage('妮娅', '立绘'),
    stats: calculateDerivedStats(6, 'sage', { str: 1, dex: 5, vit: 4, int: 10, spr: 6 }, ['note-string'], 'human'),
    experience: 120,
    nextLevelExperience: 600,
    availableAttributePoints: 0,
    favorability: 0,
    relationshipStage: '陌生',
    equipmentIds: ['note-string', 'student-robe'],
    activeSkillIds: ['nia-risk-stamp', 'sage-page-reading'],
    knownSkillIds: ['nia-risk-stamp', 'sage-page-reading', 'sage-short-ward'],
    attributes: ['行会公告板维护权', '风险印章', '结算担保登记'],
    skills: ['nia-risk-stamp', 'sage-page-reading'],
  }),
  npc({
    id: 'npc-patchi',
    name: '帕琪',
    fullName: '七旗议会书记员帕琪',
    type: 'NPC登记',
    race: '侏儒',
    raceId: 'gnome',
    gender: '女',
    age: 26,
    affiliation: '岚之领七城邦',
    identity: '会议记录与日程表保管人',
    classId: 'sage',
    profession: '议会书记员',
    avatarUrl: characterImage('帕琪', '头像'),
    portraitUrl: characterImage('帕琪', '立绘'),
    stats: calculateDerivedStats(5, 'sage', { str: 1, dex: 5, vit: 4, int: 10, spr: 5 }, ['note-string'], 'gnome'),
    experience: 200,
    nextLevelExperience: 500,
    availableAttributePoints: 0,
    favorability: 0,
    relationshipStage: '陌生',
    equipmentIds: ['note-string', 'student-robe'],
    activeSkillIds: ['patchi-page-reset', 'sage-page-reading'],
    knownSkillIds: ['patchi-page-reset', 'sage-page-reading'],
    attributes: ['七旗日期表', '停会铃', '临时会议空页'],
    skills: ['patchi-page-reset', 'sage-page-reading'],
  }),
  npc({
    id: 'npc-sara',
    name: '萨菈',
    fullName: '灰雾边境医师萨菈',
    type: 'NPC登记',
    race: '精灵',
    raceId: 'elf',
    gender: '女',
    age: 29,
    affiliation: '灰雾边境营地',
    identity: '龙脉灼伤记录人',
    classId: 'alchemist',
    profession: '边境医师',
    avatarUrl: characterImage('萨菈', '头像'),
    portraitUrl: characterImage('萨菈', '立绘'),
    stats: calculateDerivedStats(8, 'alchemist', { str: 1, dex: 4, vit: 7, int: 12, spr: 8 }, ['corked-vial-kit', 'field-robe'], 'elf'),
    experience: 240,
    nextLevelExperience: 800,
    availableAttributePoints: 0,
    favorability: 0,
    relationshipStage: '陌生',
    equipmentIds: ['corked-vial-kit', 'field-robe', 'herb-satchel'],
    activeSkillIds: ['sara-burn-triage', 'alchemist-stable-dose', 'priest-clean-light'],
    knownSkillIds: ['sara-burn-triage', 'alchemist-stable-dose', 'priest-clean-light'],
    attributes: ['边境病棚处置权', '瘴气病册', '药草批次'],
    skills: ['sara-burn-triage', 'alchemist-stable-dose', 'priest-clean-light'],
  }),
  npc({
    id: 'npc-lucy',
    name: '露西',
    fullName: '星砂学院观测员露西',
    type: 'NPC登记',
    race: '镜裔',
    raceId: 'mirrorborn',
    gender: '女',
    age: 27,
    affiliation: '星砂学院邦',
    identity: '观星塔夜班记录人',
    classId: 'sage',
    profession: '观测员',
    avatarUrl: characterImage('露西', '头像'),
    portraitUrl: characterImage('露西', '立绘'),
    stats: calculateDerivedStats(9, 'sage', { str: 1, dex: 6, vit: 4, int: 14, spr: 8 }, ['chalk-oak-staff', 'student-robe'], 'mirrorborn'),
    experience: 360,
    nextLevelExperience: 900,
    availableAttributePoints: 0,
    favorability: 0,
    relationshipStage: '陌生',
    equipmentIds: ['chalk-oak-staff', 'student-robe', 'calibration-lamp'],
    activeSkillIds: ['lucy-spectrum-shift', 'sage-spark-formula', 'summoner-contract-mark'],
    knownSkillIds: ['lucy-spectrum-shift', 'sage-spark-formula', 'summoner-contract-mark'],
    attributes: ['观星塔夜班记录', '星砂仪器校准', '断线光谱'],
    skills: ['lucy-spectrum-shift', 'sage-spark-formula', 'summoner-contract-mark'],
  }),
  npc({
    id: 'npc-fiora',
    name: '绯欧菈',
    fullName: '绯欧菈·冯·艾登海姆',
    type: 'NPC登记',
    race: '人类',
    raceId: 'human',
    gender: '女',
    age: 21,
    affiliation: '艾琳西亚圣骑士团',
    identity: '圣骑士团团长',
    classId: 'paladin',
    profession: '圣骑士团团长',
    avatarUrl: characterImage('绯欧菈', '头像'),
    portraitUrl: characterImage('绯欧菈', '立绘'),
    stats: calculateDerivedStats(16, 'paladin', { str: 17, dex: 5, vit: 11, int: 3, spr: 9 }, ['worn-long-sword', 'patched-round-shield', 'travel-mail'], 'human'),
    experience: 900,
    nextLevelExperience: 1600,
    availableAttributePoints: 0,
    favorability: 0,
    relationshipStage: '陌生',
    equipmentIds: ['worn-long-sword', 'patched-round-shield', 'travel-mail', 'dawn-shield-fragment'],
    activeSkillIds: ['fiora-guardian-oath', 'paladin-oath-cut', 'paladin-guard-step'],
    knownSkillIds: ['fiora-guardian-oath', 'paladin-oath-cut', 'paladin-guard-step', 'paladin-bell-aid'],
    attributes: ['圣骑士团指挥权', '黎明城墙救援记录调阅', '拂晓之盾旧誓页'],
    skills: ['fiora-guardian-oath', 'paladin-oath-cut', 'paladin-guard-step'],
  }),
  npc({
    id: 'npc-kohara',
    name: '小原',
    fullName: '水蓝贤者小原',
    type: 'NPC登记',
    race: '人类',
    raceId: 'human',
    gender: '女',
    age: '未知',
    affiliation: '魔法协会',
    identity: '魔法协会名誉副会长',
    classId: 'sage',
    profession: '云游贤者',
    avatarUrl: characterImage('小原', '头像'),
    portraitUrl: characterImage('小原', '立绘'),
    stats: calculateDerivedStats(18, 'sage', { str: 0, dex: 5, vit: 5, int: 20, spr: 19 }, ['chalk-oak-staff', 'star-cup-echo'], 'human'),
    experience: 1200,
    nextLevelExperience: 1800,
    availableAttributePoints: 0,
    favorability: 0,
    relationshipStage: '陌生',
    equipmentIds: ['chalk-oak-staff', 'student-robe', 'star-cup-echo'],
    activeSkillIds: ['kohara-primal-spring', 'lucy-spectrum-shift'],
    knownSkillIds: ['kohara-primal-spring', 'lucy-spectrum-shift', 'sage-soft-mend', 'sage-short-ward'],
    attributes: ['水冰魔法', '治疗魔法', '原初清泉'],
    skills: ['kohara-primal-spring', 'lucy-spectrum-shift'],
  }),
];

export const eldredQuests: Quest[] = [
  { id: 'q1', title: '折断的剑旧账本日期', source: '七旗城风铃行会街', task: '到折断的剑酒馆核对旧账本夹层、欠款墙和七旗短账纸，把同日风声写成可结算记录。', recLevel: 3, risk: '低', reward: '两日食宿，行会登记章，七旗城声望+5', timeLimit: '2日', reputationRegionId: 'seven-banners', reputationReward: 5 },
  { id: 'q2', title: '白冠西门名册复核', source: '白冠西门登记员', task: '协助贝尔娜核验一条入城名册、泥脚印板和通行火漆，确认灾民日期栏是否被错抄。', recLevel: 5, risk: '中', reward: '入城担保便笺，基础治疗券，白冠王都声望+4', timeLimit: '当日', reputationRegionId: 'white-crown', reputationReward: 4 },
  { id: 'q3', title: '灰雾病棚药草批次', source: '灰雾边境营地医师', task: '替萨菈追回一批被错送到洗靴棚的药草，并记录龙脉灼伤样本的来源地点。', recLevel: 8, risk: '高', reward: '防瘴药两份，向导折扣，边境声望+8', timeLimit: '3日', reputationRegionId: 'gray-mist', reputationReward: 8 },
  { id: 'q4', title: '观星塔断线光谱', source: '星砂学院观星塔', task: '帮助露西整理夜班观测册，把观星塔断线光谱与灯塔暗光、极光色带残抄做第一次日期对照。', recLevel: 10, risk: '中', reward: '学院旁听许可，光谱纸副本，星砂学院邦声望+6', timeLimit: '5日', reputationRegionId: 'star-sand', reputationReward: 6 },
];

export const eldredCombatUnits: CombatUnit[] = [
  {
    id: 'npc-nia-support',
    name: '妮娅的柜台支援',
    isEnemy: false,
    level: 6,
    hp: 32,
    maxHp: 32,
    mp: 20,
    maxMp: 20,
    ac: 12,
    stats: { str: 1, dex: 5, vit: 4, int: 10, spr: 6 },
    skillIds: ['nia-risk-stamp'],
    equipmentIds: ['note-string'],
    ap: 1,
    maxAp: 1,
    shield: 0,
    statusLogs: ['风险印章', '委托复核'],
  },
  {
    id: 'slime-door',
    name: '堵门史莱姆',
    isEnemy: true,
    level: 2,
    hp: 18,
    maxHp: 18,
    mp: 0,
    maxMp: 0,
    ac: 10,
    stats: { str: 3, dex: 2, vit: 4, int: 0, spr: 1 },
    skillIds: [],
    equipmentIds: [],
    ap: 1,
    maxAp: 1,
    shield: 0,
    statusLogs: ['黏液堵门', '吞纸'],
  },
];

export { skills };
